### ISSUE TITLE
CypressError: `cy.task('moveSnapshot')` failed

### ISSUE THREAD

**Issue by BrannonR** [cypress-visual-regression/cypress-visual-regression#174]
When running the Base image command, Im getting the following error. 

Any help is greatly apricated, thank you!  

CypressError: `cy.task('moveSnapshot')` failed with the following error:

The 'task' event has not been registered in the setupNodeEvents method. You must register it before using cy.task()

Fix this in your setupNodeEvents method here:
C:\Users\ASET\Desktop\cypress-automation-framework\cypress.config.js

https://on.cypress.io/api/task
      at <unknown> (https://vis.main.team/__cypress/runner/cypress_runner.js:141549:80)
      at tryCatcher (https://vis.main.team/__cypress/runner/cypress_runner.js:8914:23)
      at Promise._settlePromiseFromHandler (https://vis.main.naerm.team/__cypress/runner/cypress_runner.js:6849:31)
      at Promise._settlePromise (https://vis.main.team/__cypress/runner/cypress_runner.js:6906:18)
      at Promise._settlePromise0 (https://vis.main.team/__cypress/runner/cypress_runner.js:6951:10)
      at Promise._settlePromises (https://vis.main.team/__cypress/runner/cypress_runner.js:7027:18)
      at _drainQueueStep (https://vis.main.team/__cypress/runner/cypress_runner.js:3621:12)
      at _drainQueue (https://vis.main.team/__cypress/runner/cypress_runner.js:3614:9)
      at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://vis.main.naerm.team/__cypress/runner/cypress_runner.js:3630:5)
      at Async.drainQueues (https://vis.main.team/__cypress/runner/cypress_runner.js:3500:14)
  From Your Spec Code:
      at Context.eval (webpack:///./node_modules/cypress-visual-regression/dist/command.js:40:0)

**Comment by BrannonR** [comment]
I ended up redoing my config file and I fixed the problem.

**Comment by BrannonR** [comment]
> What did you change? I have the same error

@Karl-Cool I dont remember what it was exactly, but here is how I have my config. I think it was my Directory paths. 

{
            "ALWAYS_GENERATE_DIFF": false,
            SNAPSHOT_BASE_DIRECTORY: 'cypress/snapshots/base',
            SNAPSHOT_DIFF_DIRECTORY: 'cypress/snapshots/diff',
            screenshotsFolder: './cypress/snapshots/actual',
            trashAssetsBeforeRuns: true,
            video: false
        },
