### ISSUE TITLE
e2e.setupNodeEvents() function:  TypeError: (0 , plugin_1.default) is not a function

### ISSUE THREAD

**Issue by JohnBerendsenQA** [cypress-visual-regression/cypress-visual-regression#185]
I wanted to start implementing cypress-visual-regression in our project and followed your readme.  When I try to run the test however it fails with underneath error. Do you guys have any idea what causes this and how it could be fixed. Any help will be greatly appreciated.

```
Opening Cypress...
Your configFile threw an error from: /Users/johnberendsen/Documents/DTS/eidc-web/cypress.config.ts

The error was thrown while executing your e2e.setupNodeEvents() function:

TypeError: (0 , plugin_1.default) is not a function
    at setupNodeEvents (/Users/johnberendsen/Documents/DTS/eidc-web/cypress.config.ts:16:32)
    at /Users/johnberendsen/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:118:14
    at tryCatcher (/Users/johnberendsen/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/johnberendsen/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/method.js:39:29)
    at RunPlugins.load (/Users/johnberendsen/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:115:9)
    at RunPlugins.runSetupNodeEvents (/Users/johnberendsen/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:276:10)
    at EventEmitter.<anonymous> (/Users/johnberendsen/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js:185:22)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.emit (node:domain:489:12)
    at process.<anonymous> (/Users/johnberendsen/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:33:22)
    at process.emit (node:events:513:28)
    at process.emit (node:domain:489:12)
    at process.emit.sharedData.processEmitHook.installedValue [as emit] (/Users/johnberendsen/Library/Caches/Cypress/11.0.0/Cypress.app/Contents/Resources/app/node_modules/@cspotcode/source-map-support/source-map-support.js:745:40)
    at emit (node:internal/child_process:937:14)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

cypress/tsconfig.json:
```
{
  "extends": "../tsconfig.json",
  "include": ["**/*.ts"],
  "compilerOptions": {
    "sourceMap": false,
    "types": [
      "cypress",
      "cypress-visual-regression"
    ],
    "resolveJsonModule": true,  
    "noPropertyAccessFromIndexSignature" : false,
    "strictNullChecks": false,
    "esModuleInterop": true
  }
}
```

cypress.config.ts:
```
import { defineConfig } from 'cypress';
import getCompareSnapshotsPlugin from 'cypress-visual-regression/dist/plugin';

export default defineConfig({
  env: {
    screenshotsFolder: './cypress/snapshots/actual',
    trashAssetsBeforeRuns: true,
    failSilently: false,
    video: false,
    ALLOW_VISUAL_REGRESSION_TO_FAIL: true,
    SNAPSHOT_BASE_DIRECTORY: './cypress/basesnapshots',
    SNAPSHOT_DIFF_DIRECTORY: './cypress/snapshots/dif',
  },
  e2e: {
    setupNodeEvents(on, config) {
      getCompareSnapshotsPlugin(on, config);
    },
    baseUrl: 'http://localhost:4200',
    specPattern: 'cypress/e2e',
    videosFolder: 'cypress/videos',
    screenshotsFolder: 'cypress/screenshots',
    fixturesFolder: 'cypress/fixtures',
    reporter: 'junit',
    reporterOptions: {
      mochaFile: 'cypress-reports/fixture-[hash].xml',
    },
  },
});
```

cypress/support/commands.ts:
```
import compareSnapshotCommand from 'cypress-visual-regression/dist/command';

compareSnapshotCommand({
  capture: 'fullPage',
});
```

cypress/support/e2e.ts:
`import './commands';`

**Comment by FurtunaDaniel** [comment]
same here

**Comment by FurtunaDaniel** [comment]
Hey @JohnBerendsenQA ,
Try to add "esModuleInterop": true to your cypress/tsconfig.json
This worked for me.
This issue was fixed previously https://github.com/cypress-visual-regression/cypress-visual-regression/issues/154

**Comment by JohnBerendsenQA** [comment]
@FurtunaDaniel Tried this but still its throwing the same error. 

My cypress/tsconfig.json now looks like this:

{
  "extends": "../tsconfig.json",
  "include": ["**/*.ts"],
   "esModuleInterop": true,
  "compilerOptions": {
    "sourceMap": false,
    "types": [
      "cypress",
      "cypress-visual-regression"
    ],
    "resolveJsonModule": true,  
    "noPropertyAccessFromIndexSignature" : false,
    "strictNullChecks": false,
  }
}

**Comment by aryltsov** [comment]
same problem, but who cares ...

**Comment by ruimarques-lseg** [comment]
@JohnBerendsenQA esModuleInterop needs to be inside compilerOptions:

```
"compilerOptions": {
      "esModuleInterop": true,
}
```

**Comment by moshfeu** [comment]
I guess this issue can be closed now

**Comment by mduivcap** [comment]
I'm getting a similar error, but the above mentioned solution does not resolve it for me

![image](https://github.com/cypress-visual-regression/cypress-visual-regression/assets/127507539/79b529f9-0033-4caf-90a8-38f641d74da5)

Print to console shows me
```
TypeError: The following error originated from your test code, not from Cypress.

  > (0 , command_1.default) is not a function

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
    at ./cypress/support/commands.ts (webpack:///./cypress/support/commands.ts:29:0)
    at __webpack_require__ (webpack:///webpack/bootstrap:19:0)
    at ./cypress/support/e2e.ts (webpack:///./cypress/support/e2e.ts:18:0)
    at __webpack_require__ (webpack:///webpack/bootstrap:19:0)
    at 0 (https://example.cypress.io/__cypress/tests?p=cypress\support\e2e.ts:313:18)
    at __webpack_require__ (webpack:///webpack/bootstrap:19:0)
    at eval (webpack:///webpack/bootstrap:83:0)
    at eval (https://example.cypress.io/__cypress/tests?p=cypress\support\e2e.ts:87:10)
    at eval (<anonymous>)
From previous event:
    at evalScripts (https://example.cypress.io/__cypress/runner/cypress_runner.js:168477:58)
    at <unknown> (https://example.cypress.io/__cypress/runner/cypress_runner.js:168486:152)
From previous event:
    at runScriptsFromUrls (https://example.cypress.io/__cypress/runner/cypress_runner.js:168486:136)
    at Object.runScripts (https://example.cypress.io/__cypress/runner/cypress_runner.js:168527:12)
    at $Cypress.onSpecWindow (https://example.cypress.io/__cypress/runner/cypress_runner.js:157107:75)
logError @ index-bb733681.js:112167
(anonymous) @ index-bb733681.js:124401
emit2 @ index-bb733681.js:117863
(anonymous) @ cypress_runner.js:188745
emit @ cypress_runner.js:28198
emit @ cypress_runner.js:188808
onPrint @ cypress_runner.js:187623
_onPrintClick @ cypress_runner.js:187627
(anonymous) @ cypress_runner.js:188929
executeAction @ cypress_runner.js:54695
n @ cypress_runner.js:54695
ca @ cypress_runner.js:65341
ja @ cypress_runner.js:65342
ka @ cypress_runner.js:65342
wa @ cypress_runner.js:65344
Aa @ cypress_runner.js:65345
ya @ cypress_runner.js:65345
Da @ cypress_runner.js:65348
Ad @ cypress_runner.js:65411
Gi @ cypress_runner.js:65577
Kb @ cypress_runner.js:65366
Dd @ cypress_runner.js:65413
(anonymous) @ cypress_runner.js:65578
../../node_modules/scheduler/cjs/scheduler.production.min.js.exports.unstable_runWithPriority @ cypress_runner.js:69104
Ii @ cypress_runner.js:65578
Cd @ cypress_runner.js:65412
```

commands.ts
```javascript
import compareSnapshotCommand from 'cypress-visual-regression/dist/command';
compareSnapshotCommand();   //this is line 29 that is mentioned in the error of the screenshot
```

cypress.config.ts
```javascript
import { defineConfig } from 'cypress';
import getCompareSnapshotsPlugin from 'cypress-visual-regression/dist/plugin';
export default defineConfig({
  video: false,
  env: {
    screenshotsFolder: './cypress/snapshots/actual',
    trashAssetsBeforeRuns: true,
    video: false,
    failSilently: false,
  },
  e2e: {
    baseUrl: '<some-url>',
    setupNodeEvents(on, config) {
      getCompareSnapshotsPlugin(on, config);
    },
  },
});
```

e2e.ts
`import './commands'`

tsconfig.json
```javascript
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "es5",
      "dom"
    ],
    "strict": true,
    "types": [
      "cypress",
      "cypress-visual-regression"
    ]
  },
  "include": [
    "**/*.ts"
  ],
  "esModuleInterop": true
}
```
