### ISSUE TITLE
Error: Snapshot does not exist after upgrade from 2.1.1 to 3.0.0

### ISSUE THREAD

**Issue by skjnldsv** [cypress-visual-regression/cypress-visual-regression#193]
Hi, on upgrade from 2.1.1 to 3.0.0, I experience an issue.
See run: https://github.com/nextcloud/viewer/actions/runs/4805912110/jobs/8553138180

```
  3) Visual regression tests 
       Take test-card.png screenshot 2:
     Error: Snapshot /home/runner/work/viewer/viewer/cypress/snapshots/base/visual-regression.cy.js/image2.png does not exist.
      at <unknown> (/home/runner/work/viewer/viewer/node_modules/cypress-visual-regression/dist/utils.js:62:14)
      at new Promise (<anonymous>:null:null)
      at parseImage (/home/runner/work/viewer/viewer/node_modules/cypress-visual-regression/dist/utils.js:60:10)
      at compareSnapshotsPlugin (/home/runner/work/viewer/viewer/node_modules/cypress-visual-regression/dist/plugin.js:86:31)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

## Config
```ts
    // Visual regression testing
	env: {
		failSilently: false,
		type: 'actual',
	},
	screenshotsFolder: 'cypress/snapshots/actual',
	trashAssetsBeforeRuns: true,

	e2e: {
		async setupNodeEvents(on, config) {
			getCompareSnapshotsPlugin(on, config)
```

## Snapshot content
https://github.com/nextcloud/viewer/actions/runs/4805912110/jobs/8553138180
https://github.com/nextcloud/viewer/tree/master/cypress/snapshots/base/visual-regression.cy.js
![image](https://user-images.githubusercontent.com/14975046/234503722-967cfde3-03fc-4728-a8dc-48341e4300c1.png)

**Comment by skjnldsv** [comment]
So, I did see that there is a removal of the suffix: https://github.com/cypress-visual-regression/cypress-visual-regression/pull/172

But when regenerating the snapshots, the generated files still have the suffix :thinking:

**Comment by skjnldsv** [comment]
AAAaaaand of course I just found the issue, I added the snapshot folder to gitignore to prevent unwanted update of the base files...
And I forgot to git add with `--force`, so I did not in fact updated the snapshot base file names....
