### ISSUE TITLE
CypressError: `cy.task()` must only be invoked from the spec file or support file.

### ISSUE THREAD

**Issue by heteibako** [cypress-visual-regression/cypress-visual-regression#249]
I have an issue with the compareSnapshot command. It goes through locally but fails in the GitLab pipeline.

`CypressError: `cy.task()` must only be invoked from the spec file or support file.`

```
From Your Spec Code:
      at compareScreenshots (webpack://@project-cypress/./node_modules/cypress-visual-regression/dist/command.js:165:0)
      at Context.eval (webpack://@project-cypress/./node_modules/cypress-visual-regression/dist/command.js:72:0)
```

I am using React with Vite

"cypress": "13.12.0",
"cypress-visual-regression": "5.0.2",

cypress.config.snapshot.ts:

```
import { defineConfig } from 'cypress';
import { configureVisualRegression } from 'cypress-visual-regression';

export default defineConfig({
    e2e: {
        reporter: 'cypress-multi-reporters',
        chromeWebSecurity: false,
        reporterOptions: {
            configFile: 'reporter-config-snapshot.json'
        },
        retries: {
            runMode: 2
        },
        experimentalModifyObstructiveThirdPartyCode: true,
        video: false,
        videoCompression: 32,
        viewportWidth: 1280,
        viewportHeight: 720,
        fixturesFolder: 'fixtures',
        videosFolder: 'cypress/videos',
        screenshotsFolder: './cypress/screenshots/actual',
        trashAssetsBeforeRuns: true,
        defaultCommandTimeout: 6000,
        setupNodeEvents,
        baseUrl: 'http://localhost:3000',
        specPattern: 'integration/**/*.snapshot.js',
        supportFile: 'support/snapshotSupport.js',
        env: {
           baseUrl: 'http://localhost:3000',
           visualRegressionType: 'regression',
           visualRegressionBaseDirectory: 'cypress/snapshot/base',
           visualRegressionDiffDirectory: 'cypress/snapshot/diff',
           visualRegressionGenerateDiff: 'always',
           visualRegressionFailSilently: true
    }
 },
    
});

async function setupNodeEvents(
    on: Cypress.PluginEvents,
    config: Cypress.PluginConfigOptions
): Promise<Cypress.PluginConfigOptions> {
    configureVisualRegression(on);

    return config;
}
```

support/snapshotSupport.js

```
import './commands';

const { addCompareSnapshotCommand } = require('cypress-visual-regression/dist/command');
addCompareSnapshotCommand({
    capture: 'fullPage',
    scale: false
});
```

Thanks in advance for your help.

**Comment by Zaista** [comment]
I can't reproduce this, I even cloned the example project for React+Vite+Cypress from [here ](https://github.com/nefayran/cypress-react-vite) and tried it, it works without issues.

Could you please provide an example project where this is reproducable?

**Comment by heteibako** [comment]
We have migrated from Cypress. thanks. Not relevant anymore
